### ISSUE TITLE
Visualize gaps in Review History chart

### ISSUE THREAD

**Issue by sclu1034** [ranger-ross/nihongo-stats#151]
Currently, the Review History chart simply draws one bar for each day when there were reviews and disregards the relation/distance between those days. Missed days are only noticeable when you hover over two adjacent bars and compare the dates.

I think it would be nice to (have the option to) visualize gaps in review days. This could be done with a dropdown:
- don't show (as it is right now)
- draw a line/short gap as separator regardless of how long the break was
- draw empty bars for every empty day

**Comment by ranger-ross** [comment]
1. thank you for reporting this.

2. frankly, I think this is just a bug. I feel like the best default behavior would be to show a gap when you did have/do reviews. I don't really see much value in hiding periods where you did not have reviews.


I found where the bug is and will open a BugFix PR shortly
