### ISSUE TITLE
[Bug] Showing ? instead of radical

### ISSUE THREAD

**Issue by flamerged** [ranger-ross/nihongo-stats#299]
<img width="391" alt="image" src="https://user-images.githubusercontent.com/34665379/195985007-05b7d2f1-1b95-4dce-ba20-cc355d50f623.png">

There are some radicals in wanikani-items that only show a question mark. Not sure if this is on my side because of fonts or some bug on the website. I don't have the same issue on wkstats though.

**Comment by ranger-ross** [comment]
So for context on this:

The reason this happens is because not all radicals on Wanikani are actual a character that can be represented in ASCII. 

For example the gun [radical](https://www.wanikani.com/radicals/gun) is not a character so when the radical data is request from the Wanikani API, its responds with no characters.

<img width="861" alt="image" src="https://user-images.githubusercontent.com/25847436/196012926-866701c8-29f5-4ef0-bb8d-ff98817864c4.png">

On WKStats, it only displays Kanji (not radicals or Vocab), so it does not have this problem.

For the solution, the WK API does provide links to SVG files so it may be possible display the SVG file if the radical does not have characters. The tricky part will be making it match the styling of the other items.
